name: Build and pack DevExtreme npm packages

on:
  pull_request:
    paths-ignore:
      - 'apps/**/*.md'
  push:
    branches: [25_1]

jobs:
  build:
    runs-on: devextreme-shr2

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ env.STORE_PATH }}
            .nx/cache
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Build npm packages
        run: pnpm run all:build

      - name: Copy build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devextreme-npm-packages
          path: |
            artifacts/npm/*.tgz
          retention-days: 1

  custom_bundles:
    runs-on: devextreme-shr2
    needs: build

    steps:
      - name: Download npm packages
        uses: actions/download-artifact@v4
        with:
          name: devextreme-npm-packages
          path: npm

      - name: Move devextreme package
        run: mv ./npm/devextreme-2*.tgz ./devextreme.tgz

      - name: Setup deps
        run: |
          npm init -y
          npm i webpack terser-webpack-plugin
          npm i ./devextreme.tgz

      - name: Build bundle
        run: |
          npx devextreme-bundler-init custom-bundle
          npx devextreme-bundler custom-bundle